### ISSUE TITLE
Problems with transpilation using axion 0.20

### ISSUE THREAD

**Issue by walter-bd** [iHub-PTI/boldo-server#9]
### Scenario: 
You try to run 
`npm install`
`npm run build`
Error:
`node_modules/axios/index.d.ts(62,38): error TS2304: Cannot find name 'ProgressEvent'.`
Related to: 
[https://github.com/axios/axios/issues/3219](https://github.com/axios/axios/issues/3219)
Solution:
Downgrade to axion 0.19 or upgrade to axion 0.21

**Comment by pA1nD** [comment]
already fixed via  https://github.com/iHub-PTI/boldo-server/commit/0ebe1dc19774d9e8512864337752eb3a6fd98863
